# Generated by Django 6.0.3 on 2026-03-23 19:16

import apps.anuncios.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_negociavel', models.BooleanField(default=False)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('recondicionado', 'Recondicionado')], default='usado', max_length=20)),
                ('provincia', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('expirado', 'Expirado'), ('eliminado', 'Eliminado'), ('rejeitado', 'Rejeitado')], default='activo', max_length=20)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('contactos_recebidos', models.PositiveIntegerField(default=0)),
                ('auto_renovar', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField(default=apps.anuncios.models.expiracao_padrao)),
                ('publicado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='categorias.categoria')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='anuncios.anuncio')),
            ],
            options={
                'verbose_name': 'Imagem do anúncio',
                'verbose_name_plural': 'Imagens do anúncio',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='AtributoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='anuncios.anuncio')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.atributocategoria')),
            ],
            options={
                'verbose_name': 'Atributo do anúncio',
                'unique_together': {('anuncio', 'atributo')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='anuncios.anuncio')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorito',
                'unique_together': {('utilizador', 'anuncio')},
            },
        ),
    ]
