# Generated by Django 6.0.3 on 2026-06-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Atributo do anúncio',
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Favorito',
            },
        ),
        migrations.CreateModel(
            name='ImagemAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='anuncios/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('principal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Imagem do anúncio',
                'verbose_name_plural': 'Imagens do anúncio',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(max_length=2000)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preco_negociavel', models.BooleanField(default=False)),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('usado', 'Usado'), ('recondicionado', 'Recondicionado')], default='novo', max_length=20)),
                ('provincia', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente_pagamento', 'Pendente de Pagamento'), ('activo', 'Activo'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('expirado', 'Expirado'), ('eliminado', 'Eliminado'), ('rejeitado', 'Rejeitado')], default='pendente_pagamento', max_length=30)),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
                ('contactos_recebidos', models.PositiveIntegerField(default=0)),
                ('auto_renovar', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('publicado_em', models.DateTimeField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='anuncios', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['-publicado_em'],
            },
        ),
    ]
