# Generated by Django 6.0.3 on 2026-05-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='subscricao',
            field=models.ForeignKey(blank=True, help_text='Subscrição/plano que foi consumido para publicar este anúncio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_publicados', to='pagamentos.subscricaoutilizador'),
        ),
    ]
