# Generated by Django 6.0.3 on 2026-06-20 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0002_initial'),
        ('categorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atributoanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='anuncios.anuncio'),
        ),
        migrations.AddField(
            model_name='atributoanuncio',
            name='atributo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorias.atributocategoria'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='anuncios.anuncio'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagemanuncio',
            name='anuncio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='anuncios.anuncio'),
        ),
        migrations.AlterUniqueTogether(
            name='atributoanuncio',
            unique_together={('anuncio', 'atributo')},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('utilizador', 'anuncio')},
        ),
    ]
