# Generated by Django 6.0.3 on 2026-06-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_initial'),
        ('pagamentos', '0003_alter_destaqueanuncio_subscricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='subscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios_publicados', to='pagamentos.subscricaoutilizador'),
        ),
    ]
