# Generated by Django 6.0.3 on 2026-06-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0004_alter_anuncio_subscricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='condicao',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
