# Generated by Django 6.0.3 on 2026-04-07 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_dias', models.PositiveIntegerField(default=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('destaque', 'Destaque'), ('patrocinado', 'Patrocinado'), ('urgente', 'Urgente'), ('topo_pagina', 'Topo da Página')], max_length=20)),
                ('boost_visualizacoes', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano de destaque',
                'verbose_name_plural': 'Planos de destaque',
            },
        ),
        migrations.CreateModel(
            name='DestaqueAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_em', models.DateTimeField(auto_now_add=True)),
                ('fim_em', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='anuncios.anuncio')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagamentos.planodestaque')),
            ],
            options={
                'verbose_name': 'Destaque de anúncio',
            },
        ),
    ]
