# Generated by Django 6.0.3 on 2026-05-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('transferencia', 'Transferência Bancária'), ('manual', 'Confirmação Manual')], max_length=20)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('falhado', 'Falhado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_externa', models.CharField(blank=True, max_length=255)),
                ('telefone_pagamento', models.CharField(blank=True, max_length=20)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('resposta_gateway', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlanoDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_dias', models.PositiveIntegerField(default=7)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('destaque', 'Destaque'), ('patrocinado', 'Patrocinado'), ('urgente', 'Urgente'), ('topo_pagina', 'Topo da Página')], max_length=20)),
                ('boost_visualizacoes', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plano de destaque',
                'verbose_name_plural': 'Planos de destaque',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PlanoPublicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('avulso', 'Por Anúncio'), ('subscricao', 'Subscrição')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço em Meticais (MZN)', max_digits=12)),
                ('max_anuncios', models.PositiveIntegerField(blank=True, help_text='Deixar em branco para ilimitado', null=True)),
                ('duracao_anuncio_dias', models.PositiveIntegerField(default=30, help_text='Duração de cada anúncio em dias')),
                ('duracao_subscricao_dias', models.PositiveIntegerField(default=30, help_text='Validade da subscrição em dias')),
                ('max_imagens', models.PositiveIntegerField(default=6, help_text='Número máximo de imagens por anúncio')),
                ('dias_destaque_incluidos', models.PositiveIntegerField(default=0, help_text='Dias de destaque automático incluídos em cada anúncio')),
                ('activo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na página de planos')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de publicação',
                'verbose_name_plural': 'Planos de publicação',
                'ordering': ['ordem', 'preco'],
            },
        ),
        migrations.CreateModel(
            name='SubscricaoUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente de Pagamento'), ('activa', 'Activa'), ('expirada', 'Expirada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('creditos_totais', models.PositiveIntegerField(blank=True, help_text='Total de anúncios incluídos. Nulo = ilimitado.', null=True)),
                ('creditos_usados', models.PositiveIntegerField(default=0)),
                ('inicio_em', models.DateTimeField(blank=True, null=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('actualizado_em', models.DateTimeField(auto_now=True)),
                ('preco_pago', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Subscrição',
                'verbose_name_plural': 'Subscrições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DestaqueAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('plano_publicacao', 'Incluído no Plano de Publicação'), ('compra_avulsa', 'Compra Avulsa de Destaque')], default='compra_avulsa', max_length=30)),
                ('inicio_em', models.DateTimeField(auto_now_add=True)),
                ('fim_em', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destaques', to='anuncios.anuncio')),
            ],
            options={
                'verbose_name': 'Destaque de anúncio',
                'verbose_name_plural': 'Destaques de anúncios',
                'ordering': ['-inicio_em'],
            },
        ),
    ]
