# Generated by Django 6.0.3 on 2026-06-20 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscricaoutilizador',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscricoes', to='pagamentos.planopublicacao'),
        ),
        migrations.AddField(
            model_name='subscricaoutilizador',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscricoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='subscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.subscricaoutilizador'),
        ),
        migrations.AddField(
            model_name='destaqueanuncio',
            name='subscricao',
            field=models.ForeignKey(help_text='Subscrição que originou este destaque', on_delete=django.db.models.deletion.PROTECT, related_name='destaques', to='pagamentos.subscricaoutilizador'),
        ),
        migrations.AddIndex(
            model_name='subscricaoutilizador',
            index=models.Index(fields=['utilizador', 'estado', 'expira_em'], name='pagamentos__utiliza_596164_idx'),
        ),
        migrations.AddIndex(
            model_name='destaqueanuncio',
            index=models.Index(fields=['activo', 'fim_em'], name='pagamentos__activo_6842e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='destaqueanuncio',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('anuncio',), name='unique_active_destaque_per_anuncio'),
        ),
    ]
