# Generated by Django 6.0.3 on 2026-05-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destaqueanuncio',
            options={'ordering': ['-inicio_em'], 'verbose_name': 'Destaque de anúncio', 'verbose_name_plural': 'Destaques de anúncios'},
        ),
        migrations.AlterModelOptions(
            name='planodestaque',
            options={'ordering': ['nome'], 'verbose_name': 'Plano de destaque', 'verbose_name_plural': 'Planos de destaque'},
        ),
        migrations.AlterField(
            model_name='destaqueanuncio',
            name='fim_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='destaqueanuncio',
            index=models.Index(fields=['activo', 'fim_em'], name='pagamentos__activo_6842e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='destaqueanuncio',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('anuncio',), name='unique_active_destaque_per_anuncio'),
        ),
    ]
