# Generated by Django 6.0.3 on 2026-06-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('emola', 'e-Mola'), ('transferencia', 'Transferência Bancária'), ('manual', 'Confirmação Manual'), ('gratuito', 'Gratuito')], max_length=20),
        ),
    ]
