# Generated by Django 6.0.3 on 2026-06-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destaqueanuncio',
            name='subscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destaques', to='pagamentos.subscricaoutilizador'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='dias_destaque_incluidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_anuncio_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_subscricao_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='max_imagens',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscricaoutilizador',
            name='creditos_totais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
