# Generated by Django 6.0.3 on 2026-06-18 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0003_initial'),
        ('pagamentos', '0003_alter_pagamento_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='anuncio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_destaque', to='anuncios.anuncio'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='plano_destaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.planodestaque'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('subscricao', 'Subscrição'), ('destaque', 'Destaque de Anúncio')], default='subscricao', help_text='subscricao = compra de plano de publicação; destaque = destaque avulso', max_length=20),
        ),
        migrations.AlterField(
            model_name='destaqueanuncio',
            name='plano_destaque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.planodestaque'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.subscricaoutilizador'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='dias_destaque_incluidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_anuncio_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_subscricao_dias',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='max_imagens',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='subscricaoutilizador',
            name='creditos_totais',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
