# Generated by Django 6.0.3 on 2026-06-18 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_pagamento_anuncio_pagamento_plano_destaque_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='anuncio',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='plano_destaque',
        ),
        migrations.RemoveField(
            model_name='pagamento',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='destaqueanuncio',
            name='plano_destaque',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas em compras avulsas de destaque', null=True, on_delete=django.db.models.deletion.PROTECT, to='pagamentos.planodestaque'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='subscricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='pagamentos.subscricaoutilizador'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='dias_destaque_incluidos',
            field=models.PositiveIntegerField(default=0, help_text='Dias de destaque automático incluídos em cada anúncio'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_anuncio_dias',
            field=models.PositiveIntegerField(default=30, help_text='Duração de cada anúncio em dias'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='duracao_subscricao_dias',
            field=models.PositiveIntegerField(default=30, help_text='Validade da subscrição em dias'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='max_imagens',
            field=models.PositiveIntegerField(default=6, help_text='Número máximo de imagens por anúncio'),
        ),
        migrations.AlterField(
            model_name='planopublicacao',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição na página de planos'),
        ),
        migrations.AlterField(
            model_name='subscricaoutilizador',
            name='creditos_totais',
            field=models.PositiveIntegerField(blank=True, help_text='Total de anúncios incluídos. Nulo = ilimitado.', null=True),
        ),
    ]
