# Generated by Django 6.0.3 on 2026-06-20 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icone_url', models.CharField(blank=True, max_length=255)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('activa', models.BooleanField(default=True)),
                ('nivel', models.PositiveIntegerField(default=0)),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AtributoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('chave', models.SlugField(max_length=100)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número'), ('lista', 'Lista de opções'), ('booleano', 'Sim / Não')], default='texto', max_length=20)),
                ('opcoes', models.JSONField(blank=True, help_text='Para tipo lista: ["Opção 1", "Opção 2"]', null=True)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='categorias.categoria')),
            ],
            options={
                'verbose_name': 'Atributo de categoria',
                'verbose_name_plural': 'Atributos de categoria',
                'unique_together': {('categoria', 'chave')},
            },
        ),
    ]
